In [1]:
pip install polars

   ---------------------------------------- 0.0/35.9 MB ? eta -:--:--
   -------- ------------------------------- 7.3/35.9 MB 41.2 MB/s eta 0:00:01
   -------------------- ------------------- 18.6/35.9 MB 48.9 MB/s eta 0:00:01
   --------------------------------- ------ 30.4/35.9 MB 52.2 MB/s eta 0:00:01
   ---------------------------------------- 35.9/35.9 MB 44.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install humanize

Note: you may need to restart the kernel to use updated packages.


In [5]:
numpy install humanize

SyntaxError: invalid syntax (1864953055.py, line 1)

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
number=[1, 5, 8,-10, 28, 34, 567, 45.67]
array=np.array(number)

In [13]:
type(array)

numpy.ndarray

In [15]:
array

array([  1.  ,   5.  ,   8.  , -10.  ,  28.  ,  34.  , 567.  ,  45.67])

In [17]:
array.min()

-10.0

In [19]:
type(-10)

int

In [21]:
array.mean()

84.83375

In [23]:
array.std()

183.0746527333522

In [25]:
number

[1, 5, 8, -10, 28, 34, 567, 45.67]

In [27]:
array/2.5#

array([  0.4  ,   2.   ,   3.2  ,  -4.   ,  11.2  ,  13.6  , 226.8  ,
        18.268])

In [45]:
import numpy as np

numeri = [20, 85, 78, 458, 85, 12, 54, 96]
numery = np.array(numeri)
filtro=numery>400
numery[filtro]

array([458])

In [41]:
numery

array([ 20,  85,  78, 458,  85,  12,  54,  96])

In [1]:
pip install PyMySQL

Note: you may need to restart the kernel to use updated packages.


In [23]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst2_month2= [2500, 3900, 6410, 8150, 7100, 5350]
lst2_month1= [2000, 5500, 7200, 4320, 1280, 1900]

In [43]:
import numpy as np

lst = np.array(lst)
lst2_month2=np.array(lst2_month2)
lst2_month1=np.array(lst2_month1)
somma_totale = np.sum(lst)
vendite_mensili = np.array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350])
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst2_month2= [2500, 3900, 6410, 8150, 7100, 5350]
lst2_month1= [2000, 5500, 7200, 4320, 1280, 1900]

In [15]:
print(lst)

[2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]


In [45]:
minimo = np.min(lst)
minimo2 = np.min(lst2_month2)
minimo3 = np.min(lst2_month1)
massimo = np.max(lst)
massimo2 = np.max(lst2_month1)
massimo3 = np.max(lst2_month2)
somma_totale = np.sum(lst)
print("Somma totale con NumPy:", somma_totale)
vendite_maggiori = vendite_mensili[vendite_mensili > 4999]
vendite_maggiori2 = vendite_mensili[vendite_mensili > 3000]
print("Vendite mensili maggiori di 4999 oggetti:", vendite_maggiori)
print("Somma totale mese:", somma_totale)
print("Vendite mensili maggiori di 3000 oggetti:", vendite_maggiori2)
print("Valore minimo:", minimo)
print("Valore massimo:", massimo)
print("ecco il valore minimo del primo mese:", minimo2)
print("ecco il Valore massimo del primo mese:", massimo2)
print("ecco il valore minimo del secondo mese:", minimo3)
print("ecco il Valore massimo del secondo mese:", massimo3)

Somma totale con NumPy: 55610
Vendite mensili maggiori di 4999 oggetti: [5500 7200 6410 8150 7100 5350]
Somma totale mese: 55610
Vendite mensili maggiori di 3000 oggetti: [5500 7200 4320 3900 6410 8150 7100 5350]
Valore minimo: 1280
Valore massimo: 8150
ecco il valore minimo del primo mese: 2500
ecco il Valore massimo del primo mese: 7200
ecco il valore minimo del secondo mese: 1280
ecco il Valore massimo del secondo mese: 8150


In [51]:
import numpy as np 

In [53]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

In [55]:
stipendi*2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [71]:
stipendi = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
for stipendio in stipendi:
    print(stipendio * 2) 


200
400
600
800
1000
1200
1400
1600
1800
2000
